/*
 * Pakistan provinces/territories and their administrative districts, for the
 * /workshops district-registration form. KP is listed in full since it's the
 * priority region; other provinces are filled in at standard district
 * granularity. Administrative boundaries occasionally split or rename —
 * sanity-check against current provincial government sources before launch.
 */

export type ProvinceDistricts = {
  province: string;
  districts: string[];
};

export const PROVINCE_DISTRICTS: ProvinceDistricts[] = [
  {
    province: "Khyber Pakhtunkhwa",
    districts: [
      "Abbottabad",
      "Bajaur",
      "Bannu",
      "Battagram",
      "Buner",
      "Charsadda",
      "Chitral Lower",
      "Chitral Upper",
      "Dera Ismail Khan",
      "Hangu",
      "Haripur",
      "Karak",
      "Khyber",
      "Kohat",
      "Kohistan Lower",
      "Kohistan Upper",
      "Kolai-Pallas",
      "Kurram",
      "Lakki Marwat",
      "Malakand",
      "Mansehra",
      "Mardan",
      "Mohmand",
      "North Waziristan",
      "Nowshera",
      "Orakzai",
      "Peshawar",
      "Shangla",
      "South Waziristan Lower",
      "South Waziristan Upper",
      "Swabi",
      "Swat",
      "Tank",
      "Tor Ghar",
    ],
  },
  {
    province: "Punjab",
    districts: [
      "Attock",
      "Bahawalnagar",
      "Bahawalpur",
      "Bhakkar",
      "Chakwal",
      "Chiniot",
      "Dera Ghazi Khan",
      "Faisalabad",
      "Gujranwala",
      "Gujrat",
      "Hafizabad",
      "Jhang",
      "Jhelum",
      "Kasur",
      "Khanewal",
      "Khushab",
      "Lahore",
      "Layyah",
      "Lodhran",
      "Mandi Bahauddin",
      "Mianwali",
      "Multan",
      "Muzaffargarh",
      "Nankana Sahib",
      "Narowal",
      "Okara",
      "Pakpattan",
      "Rahim Yar Khan",
      "Rajanpur",
      "Rawalpindi",
      "Sahiwal",
      "Sargodha",
      "Sheikhupura",
      "Sialkot",
      "Toba Tek Singh",
      "Vehari",
    ],
  },
  {
    province: "Sindh",
    districts: [
      "Badin",
      "Dadu",
      "Ghotki",
      "Hyderabad",
      "Jacobabad",
      "Jamshoro",
      "Karachi Central",
      "Karachi East",
      "Karachi South",
      "Karachi West",
      "Kashmore",
      "Khairpur",
      "Korangi",
      "Larkana",
      "Malir",
      "Matiari",
      "Mirpur Khas",
      "Naushahro Feroze",
      "Qambar Shahdadkot",
      "Sanghar",
      "Shaheed Benazirabad",
      "Shikarpur",
      "Sujawal",
      "Sukkur",
      "Tando Allahyar",
      "Tando Muhammad Khan",
      "Tharparkar",
      "Thatta",
      "Umerkot",
    ],
  },
  {
    province: "Balochistan",
    districts: [
      "Awaran",
      "Barkhan",
      "Chagai",
      "Dera Bugti",
      "Duki",
      "Gwadar",
      "Harnai",
      "Jafarabad",
      "Jhal Magsi",
      "Kachhi",
      "Kalat",
      "Kech",
      "Kharan",
      "Khuzdar",
      "Kohlu",
      "Lasbela",
      "Lehri",
      "Loralai",
      "Mastung",
      "Musakhel",
      "Nasirabad",
      "Nushki",
      "Panjgur",
      "Pishin",
      "Quetta",
      "Sherani",
      "Sibi",
      "Sohbatpur",
      "Washuk",
      "Zhob",
      "Ziarat",
    ],
  },
  {
    province: "Islamabad Capital Territory",
    districts: ["Islamabad"],
  },
  {
    province: "Gilgit-Baltistan",
    districts: [
      "Astore",
      "Diamer",
      "Ghanche",
      "Ghizer",
      "Gilgit",
      "Hunza",
      "Kharmang",
      "Nagar",
      "Shigar",
      "Skardu",
    ],
  },
  {
    province: "Azad Jammu & Kashmir",
    districts: [
      "Bagh",
      "Bhimber",
      "Hattian Bala",
      "Haveli",
      "Kotli",
      "Mirpur",
      "Muzaffarabad",
      "Neelum",
      "Poonch",
      "Sudhanoti",
    ],
  },
];

export const PROVINCES = PROVINCE_DISTRICTS.map((p) => p.province);

export function districtsForProvince(province: string): string[] {
  return PROVINCE_DISTRICTS.find((p) => p.province === province)?.districts ?? [];
}
